### ISSUE TITLE
Make subscriptions unique

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/nc-ext-caldav-carddav-push#2]
Clients will update their subscriptions the same way they register them. Also a client could have forgotten its registration (for instance because it was re-installed) and will then register all subscriptions again.

Currently, registering a subscription always creates a new one:

```
|  1 | test    | personal        | web-push  | {"pushResource":"https:\/\/ntfy.sh\/xxxxx?up=1"} |         1719141600 |                    0 |
|  2 | test    | personal        | web-push  | {"pushResource":"https:\/\/ntfy.sh\/xxxxx?up=1"} |         1719141616 |                    0 |
|  3 | test    | personal        | web-push  | {"pushResource":"https:\/\/ntfy.sh\/xxxxx?up=1"} |         1719141659 |                    0 |
```

Instead, the pair of `(collection topic, pushResource)` should be a unique key of the subscription. If such a subscription is registered again, it should be updated instead. Later, updating could for instance mean to reset the expiration time.

See also: https://github.com/bitfireAT/webdav-push/issues/28

**Comment by JonathanTreffler** [comment]
implemented :)
